### PR TITLE
Support for thrift unions

### PR DESCRIPTION
**Pull request by samueltuckey**
Hi 
I have provided support for thrift unions in this patch.
The code is pretty straightforward and works fine with my projects.
Please add if you think the changes are appropriate.

Thanks,
Sam

### CODE REVIEW

**Comment by samueltuckey** [comment]
Ok, so probably not the best way to update.  
I found eleme/thrift-parser. This seems to be up to date with support for unions and extends. 
Also the latest version of the parser looks much more reliable.
Closing this pull request.

**Comment by windwhinny** [comment]
The code from lib/thriftParser.js is just a copy from eleme/thrift-parser. I will check if they merged my PR and import that parser as a npm dependency.

**Comment by windwhinny** [comment]
@samueltuckey we have merged your PR, sorry for the late and thanks for you support!

**Comment by ken-zlai** [comment]
I know this is an old thread, but I'm having trouble converting a union over to typescript.

**Pull request merged**
